### PR TITLE
Add conda install instructions. Closes #88

### LINKED ISSUE #88: better Installation instructions
Task is to write clear installation instructions that can be followed by novices with various computer configurations.

@kelle  & @ctheissen  - conda instructions of linux and MaxOS (with modifications for different chip types)
@adam - windows installation

For all, I'd recommend first installation of Anaconda Navigator or mini-anaconda (wls, ubuntu as back-up options?)

Windows notes:
- run all the commands from Anaconda terminal (CMD.exe in Anaconda Navigator) <-- this is critical
- [conda instructions]

Also necessary - setting environment variable to PYTHONPATH:

- For MacOS or Linux: add the following line to your ~/.bashrc (MacOS 11.X and earlier) or ~/.zshrc (MacOS 12.X and later):
-- export PYTHONPATH=/Users/adam/python_codes/pyspextool:$PYTHONPATH

Note: replace "/Users/adam/python_codes/pyspextool" with the path to your pyspextool directory.
 
- For Windows: see https://www.java.com/en/download/help/path.html for how to set environmental variables; either create or add to PYTHONPATH the pyspextool folder

Questions on conda environment
- how do users set this in jupyter notebook? if calling from Anaconda Navigator?
- how do we signal to users that they need to upgrade/install packages?

Some typical fail modalities
- installation script fails because user doesn't have write access to top level directories - sudo sometimes worked, but also resulted in installation for sudo user instead of current user; Anaconda installation fixed most of these issues
- wrong syntax for environmental variable
- missing or outdated packages - conda environment may fix this
- no pip or conda commands not recognized - anaconda installation fixed most of these issues

### PR DESCRIPTION
**Pull request by kelle**
Modifications to the README to include conda setup.

### CODE REVIEW

**Comment by kelle** [comment]
I think these instructions are a good start for users who know how to use their Terminal.  

I generated the .yml file from my own environment and so it's using Python 3.9. Do we want to change it to use 3.11? 

Someone with a windows machine will have to test. Things I'm not sure about
- will the git clone command work from the Anaconda terminal? If not, then we need to add WSL install instructions also.

**Comment by kelle** [comment]
I made a fresh environment in Python 3.11 and installed all the things.  I'm pretty happy with this. @ctheissen  and @chihchunhsu , could you give this a run through?

**Review by aburgasser — APPROVED** [review]
would like to add in regular anaconda (navigator) as an alternate option for point 1

**Comment by chihchunhsu** [comment]
I did a most recent pull but failed to find the environment

`conda env create -f environment.yml`

> Collecting package metadata (repodata.json): done
> Solving environment: failed
> 
> ResolvePackageNotFound: 
>   - xorg-libxdmcp==1.1.3=h27ca646_0
>   - keyring==24.2.0=py311h267d04e_0
>   - ncurses==6.4=h7ea286d_0
>   - libjpeg-turbo==2.1.5.1=h1a8c8d9_0
>   - libcblas==3.9.0=17_osxarm64_openblas
>   - libdeflate==1.18=h1a8c8d9_0
>   - libbrotlienc==1.0.9=h1a8c8d9_9
>   - pyyaml==6.0=py311he2be06e_5
>   - astropy==5.3.1=py311hb49d859_0
>   - lerc==4.0.0=h9a09cb3_0
>   - liblapack==3.9.0=17_osxarm64_openblas
>   - libopenblas==0.3.23=openmp_hc731615_0
>   - openssl==3.1.1=h53f4e23_1
>   - libffi==3.4.2=h3422bc3_5
>   - xorg-libxau==1.0.11=hb547adb_0
>   - libgfortran==5.0.0=12_3_0_hd922786_0
>   - readline==8.2=h92ec313_1
>   - libpng==1.6.39=h76d750c_0
>   - libzlib==1.2.13=h53f4e23_5
>   - pthread-stubs==0.4=h27ca646_1001
>   - freetype==2.12.1=hd633e50_1
>   - libblas==3.9.0=17_osxarm64_openblas
>   - tornado==6.3.2=py311heffc1b2_0
>   - yaml==0.2.5=h3422bc3_2
>   - matplotlib-base==3.7.2=py311h3bc9839_0
>   - tk==8.6.12=he1e0b03_0
>   - pandas==2.0.3=py311h9e438b8_1
>   - openjpeg==2.5.0=hbc2ba62_2
>   - libcxx==16.0.6=h4653b0c_0
>   - matplotlib==3.7.2=py311ha1ab1f8_0
>   - pyerfa==2.0.0.3=py311h4add359_0
>   - pillow==10.0.0=py311h095fde6_0
>   - lcms2==2.15=hd835a16_1
>   - libwebp-base==1.3.1=hb547adb_0
>   - numpy==1.25.1=py311hb8f3215_0
>   - kiwisolver==1.4.4=py311hd6ee22a_1
>   - libxcb==1.15=hf346824_0
>   - scipy==1.11.1=py311h93d07a4_0
>   - llvm-openmp==16.0.6=h1c12783_0
>   - bzip2==1.0.8=h3422bc3_4
>   - libexpat==2.5.0=hb7217d7_1
>   - python==3.11.4=h47c9636_0_cpython
>   - libgfortran5==12.3.0=ha3a6a3e_0
>   - brotli-python==1.0.9=py311ha397e9f_9
>   - libtiff==4.5.1=h23a1a89_0
>   - libbrotlidec==1.0.9=h1a8c8d9_9
>   - libsqlite==3.42.0=hb31c410_0
>   - ca-certificates==2023.5.7=hf0a4a13_0
>   - xz==5.2.6=h57fd34a_0
>   - contourpy==1.1.0=py311he4fd1f5_0
>   - fonttools==4.41.1=py311heffc1b2_0
>   - brotli-bin==1.0.9=h1a8c8d9_9
>   - libbrotlicommon==1.0.9=h1a8c8d9_9
>   - brotli==1.0.9=h1a8c8d9_9
>   - zstd==1.5.2=h4f39d0f_7
>

**Comment by kelle** [comment]
Dino, please open a new issue.
I agree, we should probably trim this file but we should discuss in a new issue.

**Pull request merged**
