### PR TITLE
some more updates to batch, and shifting around the test_data based on discussion on July 6

### PR DESCRIPTION
**Pull request by aburgasser**

### CODE REVIEW

**Comment by kelle** [comment]
Sorry, I'm super confused. It looks like you're moving `test_data/` into `src/`? I think that's definitely what we don't want since this data is not needed to run the code.  What is the problem you're trying to solve here?

**Comment by aburgasser** [comment]
folks who run install "lose" these data because the projects.toml only moves files in src (same issue instrument_data). this will affect test scripts on user side as code won't know where to find test_data. If not preferred, I'm happy to move back out (since I want to move totally out in either case). Let me know if a change is needed and I'll just shift the folder back to the top level

**Comment by kelle** [comment]
This is a special case -- our typical users will not need the test data. It should not be in the `src/` directory.

The students should get the directory now if they `git clone`. Then they just have to specify the path to the data just like any directory. 

If you have time/energy, I would move it to Cloudflare like I mentioned in #71.  Then they could download from there. If you don't want to mess around with configuring that at the moment, shorter term solution is to upload tar ball to Zenodo.

**Comment by kelle** [comment]
for the test scripts, the idea is that we'd get permalinks from Cloudflare and testscripts will download data as needed.

**Comment by aburgasser** [comment]
OK, I'll withdraw this pull request and create another with test data back where it was

**Pull request closed without merging**
