### PR TITLE
Updated tests to work with new test-data organization

### LINKED ISSUE #142: updating test data in submodule
We need to do an update on the test data in the submodule, as the current dataset has some extraneous files and the driver files do not conform to current state of code. It would also be helpful to organize a bit differently by separating raw and processed files so that unit tests can be done on the latter, and a full batch/integration test done on the former. 

I've placed a suggested replacement (uncompressed 2Gb) set of data at: 

https://drive.google.com/drive/folders/1QBEEmv55wdF5_dhIb22EORcRLKQ5u4yd?usp=drive_link 

at minimum, the driver_test.txt files in spex-prism/proc and uspex-prism/proc should be replaced (these can be pulled directly from the google folder above

### PR DESCRIPTION
**Pull request by kelle**
the test data folders were changed and some filenames were changed. This PR also includes some other small changes that I needed to make in order to get the tests to pass.

Closes #142

### CODE REVIEW

**Review by michaelcushing — CHANGES_REQUESTED** [review]
I think it would be easier to simply convert whatever the uses to all lowercase letters because eventually there will be other instruments.

**Review by michaelcushing — CHANGES_REQUESTED** [review]
The Vega model should not always be 5000 because other modes need different models, hence the check and making the filename each time.

**Comment by kelle** [comment]
> The Vega model should not always be 5000 because other modes need different models, hence the check and making the filename each time.

Yes, I agree, but I found this bug as part of this work; fixing it is beyond the scope of this PR.  I've opened an issue: #150 to address it.

**Comment by michaelcushing** [comment]
Maybe I am misunderstood.   Did it break?  Or were you just trying to clean up code?

**Comment by kelle** [comment]
Regarding Vega5000. I don't remember if it broke or not....I think I noticed it because my linter identified those variables (`model` and `file`) were not being used.  So I commented out their declarations to call more attention to the problem.  So yes, that change was just me cleaning the code.

**Comment by kelle** [comment]
> I think it would be easier to simply convert whatever the uses to all lowercase letters because eventually there will be other instruments.

Again, I agree, this part of the code needs attention. I just added a "quick fix".  I've opened an issue to address the larger issue more thoughtfully: #151

**Comment by kelle** [comment]
One thing I am personally working on in all my coding projects is having pull requests address one problem and to try to avoid "coding creep". This makes pull requests easier to review and to merge when they don't touch too many things at once.
Here are some documents which have influenced my approach
- https://gist.github.com/sktse/569cb192ce1518f83db58567591e3205
- https://google.github.io/eng-practices/review/developer/small-cls.html - where CL = pull reqest.

**Review by michaelcushing — APPROVED** [review]

**Pull request merged**
