### PR TITLE
try to get tests to pass

### PR DESCRIPTION
**Pull request by kelle**
At some point when LFS wasn't working, the test stopped passing. This PR is an attempt to get them to pass again.

### CODE REVIEW

**Comment by kelle** [comment]
@aburgasser , The thing which broke the tests were the changes you made to `setup.py` in [c0f61b8](https://github.com/pyspextool/pyspextool/commit/a5c50d2abf8a88cfa10e4419558f49d65b76ab7f). Could you please let me know what problem you were trying to solve by making those changes?

**Comment by aburgasser** [comment]
I was trying to get it so it didn't create an "UNKNOWN" egg when python setup.py was run, which caused an amazing number of failures. There was no name for the code specified in the setup.py file; see https://docs.python.org/3/distutils/setupscript.html

**Comment by aburgasser** [comment]
before we continue, can you confirm that you want setup to have NO information in it?

**Comment by kelle** [comment]
So I understand: what was motivating you to `python setup.py`? 

With our current setup, we're using `setuptools`, NOT `distutils`.  There should be no reason for you to execute the  `python setup.py` command. If something not working as expected, we need to find a different solution.

**Review by aburgasser — APPROVED** [review]

**Pull request merged**
