### PR TITLE
Implement use of Spectrum1D. 

### PR DESCRIPTION
**Pull request by kelle**
Addresses #51 and #47
TODO:
- [ ] figure out what `xsbginfo` is doing
- [ ] add tests for the four functions

### CODE REVIEW

**Comment by kelle** [comment]
@michaelcushing , I've taken this big one long function and turned it into  4 smaller ones. 

I've been able to figure out what everything is doing except for `xsbginfo`.  If this variable in `None`, it writes one file, but if it's `not None`, it writes two files. But it looks like both files have the same name. So, I'm confused. Could you tell me more about this variable and it's relevance to this function?

**Comment by michaelcushing** [comment]
I am assuming you mean write_aperture_fits.py is the function you are talking about?  Just ignore it at the moment as I haven't coded the extended source stuff up to need to deal with that as an output.  And how are you breaking it into four separate things since it just collects a bunch of values and fills a header?

**Comment by kelle** [comment]
To be clear, you are saying I can ignore the `xsbginfo` variable for now. I guess it stands for extended source background info? 

Try seeing if looking at this link works for visualizing what I've done: https://github.com/pyspextool/pyspextool/blob/e795714d5a9e081215a2db20185c58769efc1d47/src/pyspextool/io/write_apertures_fits.py

I've broken out these four elements as four separate functions, all called by `write_apertures_fits`
- check aperture parameters
- create aperture array
- create aperture header
- write fits

All the variables are input into `write_aperture_fits` and I only carry around the ones that are needed...which as far as I can tell, is just the array and the header.

**Comment by michaelcushing** [comment]
yes exactly, ignore it for now.  And yes it stands for extended source background information.  The link does work.  The way I code I don't see the added value of all the added functions.  Is there some added benefit from a python perspective?

**Comment by kelle** [comment]
It's not Python specific. The added benefits of modular programming are readability, re-use, and testability.  Those four functions are all doing completely different things.

**Comment by kelle** [comment]
- https://medium.com/dhiwise/benefits-of-modular-programming-and-how-to-avoid-spaghetti-mess-with-dhiwise-4f37212fa074
- http://gwentechembedded.com/the-advantages-of-modular-software-and-programming/
- https://www.ictshore.com/coding/how-to-avoid-spaghetti-code/

**Pull request closed without merging**
