### PR TITLE
Origin/updated pyproject 1

### PR DESCRIPTION
**Pull request by ctheissen**
Trying to fix tests and update pyproject files.

### CODE REVIEW

**Comment by ctheissen** [comment]
Having an issue getting the setup test to pass. Not exactly sure why because it runs fine on my own system, but I suspect is has something to do with whatever virtual environment is used to run the test on GitHub. Below is the error we are getting, but if you look at the actual test [https://github.com/pyspextool/pyspextool/blob/origin/updated-pyproject-1/tests/test_setup.py](url), you can see that the things it says are modules should actually be strings that are explicitly passed to the functions.

=========================== short test summary info ============================
ERROR tests/test_setup.py::test_spex_setup - TypeError: Parameter `instrument_name` of set_instrument has type module.  Acceptable types are str.
ERROR tests/test_setup.py::test_set_instrument_state - TypeError: Parameter `instrument_name` of set_instrument has type module.  Acceptable types are str.
========================= 22 passed, 2 errors in 3.10s =========================

This must be related to the tests being run as modules, so perhaps we need to change the format of this test? I am not extremely familiar with the testing environment on GitHub, so I will have to dig a little deeper. I mostly wanted to put this here so we have a record of the issue, and also see if anyone else has any insights. Maybe @kelle ?

**Comment by kelle** [comment]
I was having this problem as well, but I thought I had figured it out....YES, the problem is if you have a module or function named "setup".  That confuses everything. Let me see if I can find the offending file or function.

**Comment by kelle** [comment]
Yep, line 15 of `setup_utils`.  Change the name of that function to ANYTHING except `setup`.

**Comment by kelle** [comment]
I had to do the same thing in https://github.com/pyspextool/pyspextool/pull/31/files

**Comment by michaelcushing** [comment]
Ok.  I will change the name to pyspextool_setup().

-Mike

**Comment by ctheissen** [comment]
Looks like this is passing now. All tests working and we can merge anytime.

**Comment by michaelcushing** [comment]
Can I ask, I thought the whole thing about python was that you could have functions with the same names because you had modules. And as long as you import things separately there is no conflict.  

What am I missing?

No need to respond quickly.  This can always be dealt with later.

-Mike

**Review by kelle — APPROVED** [review]
Great improvements!

**Comment by ctheissen** [comment]
I think everything was already included in main. I think @michaelcushing took care of everything already without the need to merge this. I am pretty sure we can just delete this branch.

**Comment by kelle** [comment]
You can close the PR and delete the branch on your fork

**Comment by ctheissen** [comment]
It seems like all these changes were already implemented in the main branch by @michaelcushing , so this branch is getting pruned.

**Pull request closed without merging**
